clc
clear

A_COF=[];



D=dir(fullfile('/Users/GAO/Desktop/tribo_process/data','*.csv'))

for i=1:size(D,1)

    j=size(A_COF,1);
    

    s1 = getsize(fullfile('/Users/GAO/Desktop/tribo_process/data',D(i).name),[18,18]);
    data = getdata(fullfile('/Users/GAO/Desktop/tribo_process/data',D(i).name),[24,24+s1-1]);
    
    if i~=1
        data(1:s1,9) = data(1:s1,9)+A_COF(size(A_COF,1),1)+0.02; %50Hz
    end

    A_COF(j+1:s1+j,1)=data(1:s1,9);
    A_COF(j+1:s1+j,2)=data(1:s1,11);
    s2 = getsize(fullfile('/Users/GAO/Desktop/tribo_process/data',D(i).name),[24+s1+9,24+s1+9]);
    data = getdata(fullfile('/Users/GAO/Desktop/tribo_process/data',D(i).name),[24+15+s1,24+15+s1+s2-1]);
    data(1:s2,9) = data(1:s2,9)+A_COF(size(A_COF,1),1)+0.02; %50Hz
    A_COF(s1+1+j:s1+s2+j,1) = data(1:s2,9);
    A_COF(s1+1+j:s1+s2+j,2) = data(1:s2,11);

end

plot(A_COF(1:size(A_COF,1),1),A_COF(1:size(A_COF,1),2));

save(['/Users/GAO/Desktop/tribo_process/result/','result.mat'],'A_COF')

function data = getsize(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HEA4006MM8001 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a string
%  array.
%
%  HEA4006MM8001 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  hea4006mm8001 = importfile("C:\Users\shgao\OneDrive - National University of Singapore\tribometer\0427\hea 400 6mm 8_001.csv", [18, 18]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 2022-04-27 21:33:26

%% Input handling



%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Fx", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = "Fx";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Fx", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Fx", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
tribosize_string = readmatrix(filename, opts);
num_str=regexp(tribosize_string,'\d*\.?\d*','match');
data = str2double(num_str);

end


function data = getdata(filename, dataLines)

%IMPORTFILE Import data from a text file
%  HEA4006MM8001 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  HEA4006MM8001 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  hea4006mm8001 = importfile("C:\Users\shgao\OneDrive - National University of Singapore\tribometer\0427\hea 400 6mm 8_001.csv", [24, 129]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2022-04-27 21:04:34

%% Input handling



%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Fx", "Fz", "Z", "Y", "X", "V1", "V2", "V3", "T", "Ff", "COF"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable(filename, opts);

%% Convert to output type
data = table2array(data);

end